##################开发环境################

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/parsevip?useUnicode=true&characterEncoding=utf-8&useSSL=false
    data-username: root
    data-password: 123456


